"""Add encrypted_api_key to user table

Revision ID: 784aa49b37f5
Revises: 5a574a404308
Create Date: 2025-09-14 18:24:31.294024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784aa49b37f5'
down_revision: Union[str, Sequence[str], None] = '5a574a404308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_api_key')
    # ### end Alembic commands ###
